### ISSUE TITLE
Any Example as QEMU Builder or VirtualBox Builder (from an ISO)?

### ISSUE THREAD

**Issue by hswong3i** [thomasklein94/packer-plugin-libvirt#2]
I hope to replace the use of Packer QEMU Builder with your Libvirt Builder, but build from ISO so it work as like as how [QEMU Builder](https://www.packer.io/plugins/builders/qemu) or [VirtualBox Builder (from an ISO)](https://www.packer.io/plugins/builders/virtualbox/iso). 

Using https://github.com/thomasklein94/packer-plugin-libvirt/blob/main/docs/builders/libvirt.mdx#http-volume-source seems a workaround for this needs, could that be something like?
```
volume {
  pool = "default"
  name = "ubuntu-22.04-live-server-amd64.iso"
  source {
    type   = "http"
    url    = "http://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso"
  }
  format = "raw"
  bus        = "ide"
  target_dev = "cdrom"
}
```

Moreover, from https://github.com/thomasklein94/packer-plugin-libvirt/blob/main/docs/builders/libvirt.mdx#http-volume-source:
> Libvirt builder can download and restream a volume from a web source to the libvirt host. ** Important: ** The file will be downloaded from the machine running packer and without caching, it will be directly restreamed to libvirt as a volume. For moving large files, make sure you have the necessary download and upload bandwidth.

Is that possible for caching such ISO image by using Packer build-in caching system as like as how these works?
* https://www.packer.io/plugins/builders/qemu#iso_url
* https://www.packer.io/plugins/builders/virtualbox/iso#iso_url

### Background
I am using QEMU Builder or VirtualBox Builder (from an ISO) daily for my vagrant box build:
* https://github.com/alvistack/vagrant-ubuntu/blob/44bae1c/packer/libvirt-22.04/packer.json
* https://github.com/alvistack/vagrant-ubuntu/blob/44bae1c/packer/virtualbox-22.04/packer.json

But I am also heavily using virt-manager for my KVM management, using above QEMU Builder will not manageable by libvirt.

By switching to your Libvirt Builder could greatly simplify my dev notebook resource management ;-)

**Comment by thomasklein94** [comment]
Hi,
Nice to know someone else also finds my packer plugin useful even if it's in a very early stage now :) 

If I get your issue right, you want to cache remote 3rd party images on the local machine running packer.

I'm running a busy week this week, but I can try to accommodate your feature request in the near future.

I've briefly looked at your use-case, and I'm afraid you'll also need support for `boot_command` in the plugin which is also currently not supported.

I have an idea to support both, but I'm afraid I can not give you a clear timeline for now.

**Comment by thomasklein94** [comment]
I have a way to utilize [packer's download command](https://github.com/hashicorp/packer-plugin-sdk/blob/main/multistep/commonsteps/step_download.go) to retrieve and upload basically anything while utilizing packer's cache, as you wanted. I don't think the volume source type `http` sufficiently captures the feature, as it can be used to retreive and upload volumes from S3, local and other sources as well. I'm thinking about naming the volume source as `external` or `remote`, but I'm having a hard time decide as the word "remote" is kind of overloaded while external feels a bit superficial.
What do you think?

**Comment by hswong3i** [comment]
How about iso_url and iso_checksum, so sync with QEMU Builder and VirtualBox ISO Builder, in case we are also providing a similar use cases and functionality?

From my point of view, this additional feature request is a bit different from our existing implementation which mainly focus on libvirt volume related management, eg start from clone existing volume, by using http qcow2 kvm base image, etc.

What if we manage this in a more aggressive way, eg a new builder called libvirt-iso (similar as https://www.packer.io/plugins/builders/virtualbox/iso)? Isolated implementation from builder level could greatly simplify the end user daily use cases, where we could still reuse some common from our backend library point of view?

p.s. currently we manage the different from volume section, which a bit confuse for me to getting start… It looks quite different when compare with virtualbox-iso, virtualbox-ovf and virtualbox-vm or qemu… I couldn’t simply reference my existing experiences to here…

**Comment by thomasklein94** [comment]
Libvirt plugin is admittedly following a bit different route than other plugins out there by placing the [Packer HCL2 format](https://www.packer.io/guides/hcl) first, and not really care about the (legacy) JSON format. The reasons are:
- HCL is a more descriptive format
- easier to combine different use-cases
- comments
- supporting multiple files and reusability
Instead of having a lot, slightly different builder (like libvirt-iso, libvirt-clone, etc...) we can have one builder supporting a lot of different use cases by combining the different blocks, and I don't think I want to change this approach for now.

Because of these, the attribute `iso_url` and `iso_*` attributes in general does not make the same sense as it was with the flat, JSON descriptor before.

You can find an example of HCL definition with libvirt plugin [in the repo's example folder](https://github.com/thomasklein94/packer-plugin-libvirt/blob/main/example/).

**Comment by thomasklein94** [comment]
The latest [v0.3.0 release](https://github.com/thomasklein94/packer-plugin-libvirt/releases/tag/v0.3.0) have support for boot command and caches external volume sources with Packer (as described above)
