### ISSUE TITLE
Populate volume from local content

### ISSUE THREAD

**Issue by Snaipe** [thomasklein94/packer-plugin-libvirt#33]
As far as I can tell, there isn't any streamlined way to populate volume content as part of the definition of a source. Part of my motivation here is to provide an equivalent to the [`floppy_{dirs,files,contents}` options of the qemu builder](https://developer.hashicorp.com/packer/plugins/builders/qemu#floppy_files), but a bit more flexible: it would be awesome if this could generalize to cdrom content or some other disk.

As a workaround, I've been using an out-of-band makefile rule to prepare an image and have it as the source of the volume:

```hcl
volume {
  format = "raw"

  source {
    type = "external"
    urls = ["./config.iso"]
  }

  device     = "cdrom"
  target_dev = "hdd"
  bus        = "ide"
}
```

It would feel natural if we could populate volume directly from local filesystem content or inline content. To mirror the qemu `floppy_*` options, maybe something like this?

```hcl
volume {
  format = "raw"

  source {
    type  = "local"
    files = ["./a", "./b"]
    dirs = ["./c", "./d"]
    contents = {
      e = "some content"
    }
  }

  device     = "cdrom"
  target_dev = "hdd"
  bus        = "ide"
}
```

... where such a definition would prepare an image from the specified content, and upload it to the libvirt volume.

The main problem I see here is defining the format this intermediate image should be presented as. For CD-ROMs, it seems natural to build an ISO with mkisofs, whereas for a floppy it seems more natural to create an image using some version of FAT (probably with mformat). I'm not sure we should leave the choice of format to just heuristics (although it'd be likely fine for defaults), and it seems weirdly redundant with the `format` field of the volume.

Thoughts?

**Comment by thomasklein94** [comment]
Hi,

I'm a bit afraid of introducing such complexities to the project, but luckily some of the parts are already implemented in the `commonsteps` package part of the Packer SDK (see cloudinit soruce type). I think we could find a way to support this feature, just let's hope it won't introduce too much complexity.

To answer your question about the format: the volume's format is the format of the volume itself as understood by Libvirt, and it could be `raw`, or `qcow` for example. The format of the image could be for example `FAT`, `VFAT`, `UDF`, or `ISO9660` for cdroms. I think any of the binary volume format could be matched to any of the image formats, so I don't think any heuristics would be necessary here.

In the upcoming weeks I think I will have more free time to try and implement something for this. If you want to implement it sooner, no problems, feel free to send PRs, even if it's just some exploratory code and it's in its early stages.

**Comment by Snaipe** [comment]
I guess my concerns around the format (or to be more precise, the filesystem format, rather than the volume format) is that it's easy to shoot oneself in the foot if the format mismatches some device types. For instance, building an ISO file containing some windows unattend config and providing it as a floppy file doesn't seem to work, because the filesystem on that floppy is likely expected to be FAT/MS-DOS FS. This just means that the user will have to provide the filesystem format explicitly in the source config (`filesystem = "fat"`?). If we're not using heuristics to guess that the user _probably_ wants the content of a floppy to be FAT-formatted by default, then it means that they'll have to always provide it explicitly.

**Comment by Snaipe** [comment]
Although, looking at commonsteps, I guess your point is to keep things a bit simpler, and make the source only suitable for either a floppy or a cdrom, since the sdk provides utils for both. So this would translate to whether the device is `floppy` or `cdrom`, and format the source appropriately, and if the device is a disk, reject the config?

**Comment by AlexisVarela** [comment]
Hello @thomasklein94,
I would like to post my problem in the following issue.
I have been trying to deploy a Windows image with libvirt for several times. I have a lot of trouble with the volume {} system despite all the examples and documentation I've read.
No matter how the volumes are configured I get the error:
![image](https://user-images.githubusercontent.com/44436514/237047248-d28977b7-31ff-4498-967d-71b710bce420.png)


Which always concerns the volume with the windows ISO.
Here is my configuration:
`artifact_volume_alias = "artifact"
    boot_devices = ["hd","cdrom"]

    volume {
        pool    = "vm_lvm"
        name    = "output"
        alias   = "artifact"
        capacity    = "20G"
        size        = "20G"
        target_dev = "sdc"
        bus = "ide"
        format ="qcow2"
    }

    volume {
        pool   = "vm_lvm"
        name   = "iso"
        alias  = "iso"
        device = "cdrom"
        source {
            type = "external"
            urls = ["file:///dev/windows-images.iso"]
            //checksum = "e0c6958e94f41163aa1ea9500825b8523136e1b8c5fc03cb7e3900858c7134ad"
        }
        target_dev = "sdb"
        bus = "sata"
        format = "raw"
    }`

Do you have any idea where the problem comes from?

**Comment by thomasklein94** [comment]
Hi @AlexisVarela ,

I can't check my theory right now, but I think in case you want to use LVM volumepools, the volume format should be `raw`, not `qcow2`. Given the error message you copied here, I would first try to set up both volume to be in `raw` format.
You can see the generated XML domain definition sent to packer by setting the environment variable `PACKER_LOG=1` and setting the `-debug` flag on packer simultaneously.

Can you try setting both volumes to use the RAW format? If you still encounter similar messages, can you please attach the full packer definition and the logs produced with `PACKER_LOG=1` and `-debug` being set?

**Comment by AlexisVarela** [comment]
Indeed I use LVM volumepools. By putting all volumes in RAW format it works. Thanks.
