### ISSUE TITLE
getting ssh address error

### ISSUE THREAD

**Issue by zimmnik** [thomasklein94/packer-plugin-libvirt#40]
Packer cannot parse qemu-agent output and crash (see file packer.log in attachment)
I have error "Build 'libvirt.provisioner-fedora' errored after 12 seconds 54 milliseconds: unexpected EOF "

- packer v.1.8.5
- packer-plugin-libvirt  v0.4.2
- libvirtd v.8.6.0
- qemu-qa v.7.0.0
- fedora 37 (host and guest)

My packer template can be found in attachment (cloud_init.cfg and  main.pkr.hcl)

If make pause in debug mode to give guest ability to boot up completely, then error isn't appear (see file packer.log.debugmode in attachment)
If use option network_address_source = "lease" then error isn't appear too.

[files.zip](https://github.com/thomasklein94/packer-plugin-libvirt/files/10764303/files.zip)

**Comment by thomasklein94** [comment]
Hi @zimmnik,

Thanks for the detailed error report. Unfortunately, I didn't had the time yet to check and debug this, but I think I can set aside a few hours this weekend to take a closer look.
Thanks for your patience.

**Comment by thomasklein94** [comment]
Hi @zimmnik,

It took me a while to find the time but finally I had the opportunity to look at this closer and I think I found and fixed the issue. You can use the latest v0.4.3 release to check it out.

**Comment by zimmnik** [comment]
Thx! I confirm the problem has gone.  Could you please tell me what was cause of problem? Is there some debug mode?
