### ISSUE TITLE
Create New Volume

### ISSUE THREAD

**Issue by ericgryan** [thomasklein94/packer-plugin-libvirt#49]
I'm having a hard time understanding how does one go about creating a volume from scratch, examples in the DOC are for cloning, importing and cloudinit. If I wanted to simply create a 90GB virtio HDD unto which the OS will be loaded, what would that look like?.

In addition, have you had any luck loading a floppy for autounnatend ?

**Comment by thomasklein94** [comment]
Hi @ericgryan,

What you are looking for is a volume without a source. An example would be:

```hcl
  volume {
    alias = "artifact"  # This instructs packer to keep this volume

    name = "my-empty-disk"
    pool = "default"

    target_dev = "vda"
    format = "qcow2"
    bus = "virtio"
    capacity = "10G"
  }
```

Combine this with other volumes to have a bootable system and provision the system you like on the new volume. Watch out: the `target_dev` is just a hint for libvirt, the actual naming of the disk might differ.

Currently there is no support for building your own floppy disks with packer, however, you can have a makefile preparing a raw disk file locally, and you can use the `external` volume source to point to that file with the `file://` protocol. A similar workaround was mentioned in #33 .

**Comment by ericgryan** [comment]
Thanks, closing !!
