### ISSUE TITLE
Missing "Output configuration" support

### ISSUE THREAD

**Issue by hswong3i** [thomasklein94/packer-plugin-libvirt#57]
Refer to #55 and my normal packer build process, I will pipeline the completed build artifact to `virt-sysprep` + vagrant packaging, e.g.:
* https://github.com/alvistack/vagrant-debian/blob/master/packer/debian-testing-libvirt/packer.json
* https://github.com/alvistack/vagrant-debian/blob/master/packer/debian-testing-virtualbox/packer.json

But currently this Libvirt plugin seems missing "Output configuration", so how could we handle that as QEMU or VirtualBox ISO? e.g.
* https://developer.hashicorp.com/packer/plugins/builders/qemu#output_directory
* https://developer.hashicorp.com/packer/plugins/builders/virtualbox/iso#output_directory

Possible code reference:
* https://github.com/search?q=repo%3Ahashicorp%2Fpacker-plugin-qemu+OutputDir&type=code
* https://github.com/search?q=repo%3Ahashicorp%2Fpacker-plugin-virtualbox%20OutputDir&type=code

P.S. I understand that the result image files are under `/var/lib/libvirt/images`, but filename is not predictable nor templatable, so I couldn't pipeline it into my on going `post-processors` steps :-(

**Comment by thomasklein94** [comment]
Hi @hswong3i,

I would like to keep this plugin agnostic to whether it is running on the same machine with libvirt daemon or not. This means that I don't have plan on supporting the `output_*` attributes  as you described.

I'm already working on adding post-processors to import and export images to and from libvirt, so you can pipe it with other providers. Please note that with libvirt, the results might not be files at all - libvirt can reference iSCSI and raw devices as volumes as well.

For your use case, when you know the pool is accessible locally in the post-processing step on a well-known filesystem pool, you can manipulate the files directly with the utilities you have mentioned. If you set the volume name, the volume names became predictable.

```hcl
locals {
  result_image = "myimage-${formatdate("YYYYMMDD", timestamp())}"
}
source "libvirt" "builder" {
  libvirt_uri = "qemu://system/"  // connect to the local libvirt daemon

  // ... configuring the builder

  volume {
    name = local.result_image
    pool = "default"
    alias = "artifact"
    type = "disk"
    // ... source config, if applicable, size/capacity
  }
}
build {
  source "libvirt.builder" {}
  post-processors {
    post-processor "artifice" { # tell packer this is now the new artifact
      files = ["/var/lib/libvirt/images/${local.result_image}"]
    }
    // ... other post-processor configs would see the files specified in the previous step
  }
}
```

Documentation of the artifice post-processor can be found [here](https://developer.hashicorp.com/packer/docs/post-processors/artifice).
