### ISSUE TITLE
can't parse 'qemu+ssh://user@host:port/system' as a libvirt uri

### ISSUE THREAD

**Issue by xwu2intel** [thomasklein94/packer-plugin-libvirt#58]
Does the builder support remote libvirtd?

**Comment by AlexisVarela** [comment]
Hello,
Can you be more specific in what you want to do ?

**Comment by xwu2intel** [comment]
I'd like to build vm images on a remote machine with libvirtd installed. 
Usually, you can use the libvirtd connection URI as follows to connect to libvirtd:

qemu+ssh://user@host:port/system

When passing this URI to the libvirt packer, the packer does not understand the format:

`can't parse 'qemu+ssh://user@host:port/system' as a libvirt uri`

The question is: does the libvirt packer support building images on a remote libvirtd server?

**Comment by ericgryan** [comment]
I totally get what you want @xwu2intel, this is the feature i'd want the most for this provider. The Terraform Provider for libvirt handles using that format for deployments but this one doesn't. I am currently having to build images locally on a windows box using the QEMU provider and QEMU for windows. Being able to build directly on a linux box from windows would be fantastic.

**Comment by xwu2intel** [comment]
Thanks for confirmation.

**Comment by thomasklein94** [comment]
Hi @xwu2intel and @ericgryan,

This plugin does support connecting to a remote libvirt daemon using the `libvirt_uri` attribute.
What is the exact `libvirt_uri` value you are trying to use?

**Comment by xwu2intel** [comment]
Really? Here is the URL string:

`qemu+ssh://_user_@_host_:_port_/system`

where _user_ is my username. _host_ is an IP address, and _port_ = 22.

**Comment by thomasklein94** [comment]
Probably [this regex](https://github.com/thomasklein94/packer-plugin-libvirt/blob/3e0d90887d96dc5cd59a383775f4faf7c458330f/libvirt-utils/libvirt_uri.go#L55) is too strict to parse your value. The current implementation only accepts lowercase letters. I'll push a fix shorty that will allow `[a-z_][-a-z0-9_]*` for username and it matches for `xwu2intel`.

**Comment by xwu2intel** [comment]
Good to know. I can workaround it for now. Thanks.

**Comment by thomasklein94** [comment]
Okay, then I will add this fix to an upcoming feature release that I plan to put out this week.

**Comment by n9seo** [comment]
Hello,

I just wanted to touch on this.  I also have this issue with it.  My libvirt kvm box is a remote box and I use libvirt_uri = "qemu+ssh://_user_@_IP_/system".  The caveat here I did not see mentioned beforehand was I am using ssh keys to auth.
When I use this URI, I get the following:

```
Build 'libvirt.example' errored after 558 microseconds: ssh transport requires keyfile parameter
```

This is only after copy paste of the example in the docs and updating the libvirt_uri.   If i use the local qemu:///system all is fine.

Of course the remote URL works fine with virsh or virt-manager.

System here is manjaro and this is a good guide on how to get remote libvirt working [here](https://wiki.archlinux.org/title/libvirt) that might be useful enough on other dists, if you need.

**Comment by X-Cli** [comment]
> I just wanted to touch on this. I also have this issue with it. My libvirt kvm box is a remote box and I use libvirt_uri = "qemu+ssh://_user_@_IP_/system". The caveat here I did not see mentioned beforehand was I am using ssh keys to auth. When I use this URI, I get the following:
> 
> ```
> Build 'libvirt.example' errored after 558 microseconds: ssh transport requires keyfile parameter
> ```

For the next person having this issue : the keyfile parameter that is mentioned in this error message is the missing libvirt_uri parameter `keyfile`.

Using the following URI works:

```
qemu+ssh://_user_@_IP_/system?keyfile=/path/to/private/key
```

The plugin is working fine at this moment for remote libvirtd connections.
