### ISSUE TITLE
UEFI support

### ISSUE THREAD

**Issue by imdunnolol** [thomasklein94/packer-plugin-libvirt#7]
Could you add support for choose machine type (q35 eg) and UEFI boot?

**Comment by thomasklein94** [comment]
Hi,

Thank you for your interest in the project. 

I'm afraid that UEFI can be really complicated if we take into account all the possible parameters and variations (see [libvirt's doc](https://libvirt.org/formatdomain.html#operating-system-booting) ). At this stage of the project, I think I wouldn't be able to properly support all of it. I'm especially concerned about NVRAMs and the support of different sources like file, network, or block devices.

However, if you can describe your use-cases and why UEFI capability is necessary for you, I can look into a possible, simpler implementation. For example, if we put aside all these options and just signal that we need "something that's UEFI", not caring about NVRAMs and NVRAM paths and loaders, etc. If I'm reading all the docs right, that can be implemented very easily by setting the `firmware` attribute on the `os` tag in the domain definition XML, and let Libvirt magically figure it out.

Supporting different machine types should be an easy one, or at least I don't remember hardcoding any PCI-only device into this plugin (yet).

I'll have more time to fool around at the middle of this week or next week, I'll see then what I can do to support you and your use case.

**Comment by imdunnolol** [comment]
Yes i was looking for simple solution by adding in XMLs os section these lines
    ```
```
<type arch='x86_64' machine='q35'>hvm</type>
    <loader readonly='yes' type='pflash'>/usr/share/OVMF/OVMF_CODE.fd</loader>
```
```
Libvirtd should take care of other things

**Comment by thomasklein94** [comment]
Sorry, I'm still caught up in the middle of other issues, but I plan to resolve this and release a new version by the end of this week.

**Comment by thomasklein94** [comment]
With the new 0.3.2 release, you can specify loaders and chipsets for the machine. The use case you mentioned above should be supported by adding these to the packer source config.
(The readonly parameter is hardcoded to `"yes"`)
```
chipset = "q35"
loader_type = "pflash"
loader_path = "/usr/share/OVMF/OVMF_CODE.fd"
```
